### ISSUE TITLE
RACA inputs

### ISSUE THREAD

**Issue by habibr** [ma-compbio/RACA#1]
Hi,

I am trying to get a hand on RACA but have not found a good tutorial on this. I am particularly looking for a guide to how the chain and net files produced. For example, I already mapped my target scaffold, newScaf.fa, to reference assembly, Ref1.fa using lastz. From this, I have newScaf_Ref1.maf alignment file. Then, there is an outgroup assembly, Out1.fa. I aligned newScaf.fa to this to get newScaf_Out1.maf.

How should I proceed from this to get the chain and net files? Could you give me a step-by-step guide please?

**Comment by ma-compbio** [comment]
Chains and nets can be generated using the code from UCSC genome browser source code. @jkimlab
